export const QUIZ_CATEGORIES = {
  Culture: [
    "Architecture",
    "Fine art",
    "Museums",
    "Mythology",
    "Philosophy",
    "Religion",
    "Theatre (High Brow)",
    "World cultures",
  ],
  Entertainment: [
    "Ballet",
    "Celebrities",
    "Classical music",
    "Film & TV Music",
    "Jazz & World Music",
    "Opera",
    "Pop music",
    "Radio",
    "Television",
    "Theatre (Popular/Musicals)",
  ],
  History: [
    "Civilisations",
    "Current Affairs",
    "Exploration",
    "Famous People (History)",
    "History",
  ],
  Lifestyle: [
    "Costume",
    "Design",
    "Fashion",
    "Food & Drink",
    "Handicrafts",
    "Health & Fitness",
    "Hobbies & Pastimes",
    "Human Body",
    "New Age Beliefs",
    "Products & Brands",
    "Tourism",
  ],
  Media: [
    "Comic strips",
    "Comic books",
    "Film",
    "Graphic novels",
    "Language",
    "Literature",
    "News Media",
    "Periodicals",
    "Social Media",
  ],
  Sciences: [
    "Exact sciences (Chemistry, Physics etc.)",
    "Fauna",
    "Flora",
    "Social sciences",
  ],
  "Sport & Games": ["Games", "Sports", "Records & achievements (in context of genre)"],
  World: [
    "Cities",
    "Human Geography",
    "Physical Geography",
    "Inventions",
    "Space",
    "Technology",
    "Transport",
  ],
};
